-- AlterTable
ALTER TABLE `address` MODIFY `addressType` ENUM('RESIDENTIAL', 'TERMINAL', 'COMMERCIAL', 'YET_TO_UPDATE') NOT NULL;

-- AlterTable
ALTER TABLE `order` MODIFY `addressType` ENUM('RESIDENTIAL', 'TERMINAL', 'COMMERCIAL', 'YET_TO_UPDATE') NOT NULL;
